### ISSUE TITLE
Cannot access the api when run on cloud

### ISSUE THREAD

**Issue by lintangsutawika** [Vetal1977/tf_serving_flask_app#1]
Hi, I tried your tutorial, it works on local, but then I wanted to put this on my digital ocean server. It keeps giving me a 404 response. What might be the problem?

**Comment by vbezgachev** [comment]
Hi!
Do you have the same stack as described [here](https://www.digitalocean.com/community/tutorials/how-to-deploy-a-flask-application-on-an-ubuntu-vps) or something different? At the moment I cannot help a lot since I do not know your configuration (OS, with/without Apache, etc.).

**Comment by lintangsutawika** [comment]
Well, I copied this repo and ran it in local which worked. But when I ran it just is on digital ocean, it gave me:
```
Not Found
The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
```

**Comment by vbezgachev** [comment]
Generally, Flask built-in server is not suitable for the production as it is - it doesn't scale well. So you need a proper Web server to serve Flask application. To my knowledge DigitalOcean does not provide a solution out of the box (in opposite to AWS Elastic Beanstalk, for instance). So you need to install WSGI server yourself (Apache, uWSGI) and configure Flask application to be hosted by the server.  
I didn't do that and I suppose that the Flask application is simply not hosted properly and is not visible to the outside. That is why you get 404 response.

**Comment by pharrellyhy** [comment]
Hi,

I just cloned your repo and run it locally which returned `"GET /tf_api HTTP/1.1" 404 -`. I just entered `http://192.168.1.17:5000/tf_api` in my browser.

**Comment by vbezgachev** [comment]
Hi @pharrellyhy ,

Could you please try `http://0.0.0.0:5000/tf_api`?

**Comment by pharrellyhy** [comment]
Hi @Vetal1977 ,

Since the flask is running on the server, so that is not gonna to work. I can run a simple test using Blueprint. 
```python
from flask import Flask
from flask import Blueprint


app = Flask(__name__)

api = Blueprint('api', __name__)


@api.route('/hello')
def hello():
    return "<h1 style='color:blue'>Hello There!</h1>"


app.register_blueprint(api, url_prefix='/api')


if __name__ == '__main__':
    app.run(debug=True, host='0.0.0.0')
```
And I get below result.
![2018-07-21 5 11 27](https://user-images.githubusercontent.com/16664753/43034141-30dfffba-8d09-11e8-825e-87469c507d1e.png)

Maybe the problem is something related to flask_restplus?

**Comment by pharrellyhy** [comment]
Since I don't need a GUI, so maybe I can get rid of flask_restplus?

**Comment by vbezgachev** [comment]
Sure, if you do not need Swagger UI, you can get rid of it. In any case, also with flask_restplus, it should work. When I find a solution, I let you know. Just to be sure, `192.168.1.17` is an address of a local machine where you want to run the application, right? And you don't use Docker.

**Comment by pharrellyhy** [comment]
Thanks. Yes, just for a quick test. If everything is going well, I will prepare a Docker.

**Comment by vbezgachev** [comment]
@pharrellyhy this is strange - your simple test with a Blueprint failed for me either. I fixed that by changing a start of the Flask application and included a port like this:
  
`application.run(debug=flask_debug, host=server_name, port=server_port)`
  
After that, it worked with and without `flask-restplus`, locally and in Docker.  

I also prepared a [docker-compose file](https://github.com/Vetal1977/tf_serving_flask_app/blob/master/docker-compose.nginx.yaml) that is much more closer to a production environment. Feel free to use it if you find it helpful.

**Comment by pharrellyhy** [comment]
Hi @Vetal1977 
Thanks for that. In my environment, I commented out ```configure_app``` method and it works, with ```flask_restplus```.  Anyway, I can get my server running.

BTW, have you noticed that it takes very long time to parse the response sent back from ```tf serving```?  Parsing response using this method ```numpy.array(result_future.result().outputs['scores'].float_val)``` can slow down the whole process 20x times in my test. If didn't call this method, just getting the result back, the total time for predicting 500 images takes ~**0.5s** (using threading to make request in async way). If did call this method, it will take ~**10s**! Do you know better way to do this? Thanks!

**Comment by vbezgachev** [comment]
Hi @pharrellyhy 
on my tests, I didn't see any performance penalties by parsing. I.e. `probs = result.outputs['scores'].float_val` and `probs = [1, 2, 3]` gave me the same response times (ca. 400 ms for the first request and 40 ms for the following requests). What is `result_future.result()` in your case?

**Comment by pharrellyhy** [comment]
Hi @Vetal1977 
Here is the code snippet I used for testing the performance.
```python
NUM_IMAGES = 500

class MultiThreading():
  def __init__(self, num_imgs, concurrency):
    self._num_tests = num_imgs
    self._concurrency = concurrency
    self._done = 0
    self._activate = 0
    self._condition = threading.Condition()

  def inc_done(self):
    with self._condition:
      self._done += 1
      self._condition.notify()

  def dec_active(self):
    with self._condition:
      self._active -= 1
      self._condition.notify()

  def throttle(self):
    with self._condition:
      while self._active == self._concurrency:
        self._condition.wait()
      self._active += 1


def main():
  start = time.time()
  inference(args.server, args.concurrency, NUM_IMAGES)
  print('Total takes: {:.4f}s'.format(time.time() - start))


def inference(hostport, concurrency, num_imgs):
  host, port = hostport
  channel = implementations.insecure_channel(host, int(port))
  stub = prediction_service_pb2.beta_create_PredictionService_stub(channel)
  multi_threading = MultiThreading(num_imgs, concurrency)

  total_t1 = 0
  total_t2 = 0
  total__t3 = 0

  for _ in range(num_imgs):
    data = []
    start = time.time()
    for _ in range(32):
      with open('test_set/test.jpg', 'rb') as f:
        data.append(f.read())
    total_t1 += time.time() - start

    start = time.time()
    request = predict_pb2.PredictRequest()
    request.model_spec.name = 'classification'
    request.model_spec.signature_name = 'predict_images'

    request.inputs['images].CopyFrom(make_tensor_proto(data, shape=[32]))
    total_t2 += time.time() - start

    multi_threading.throttle()
    start = time.time()
    result_future = stub.Predict.future(request, 5.0)
    total_t3 += time.time() - start
    # Up to here, in my case, the time elapsed is about ~0.5s

    # if I do below step, the total time elapsed will be ~10s
    # classification_score = result_future.result().outputs['classification_score']

    multi_threading.inc_done()
    multi_threading.dec_active()
```
Which part could be wrong? Thanks!

**Comment by vbezgachev** [comment]
Hi @pharrellyhy 
What I see, you create a `future` instead of calling the `Predict()` directly. Then you want to get the result of the `future` execution by calling the `result_future.result()`. If you do not make this call, you just create 500 parallel requests, which will be executed somewhen but **do not wait for results** at all.  
So in case of 0.5s you just create requests, in case of 10s - you create requests and get the results. I suppose if you put in the code `result_future.result()` you get the same time as with `result_future.result().outputs['classification_score']`

**Comment by pharrellyhy** [comment]
Hi @Vetal1977 
Yes, you're right. My mistake. 

Do you know any other approach to speed up the inference? As far as I know, batching could be a promising one but maybe not easy to use.

**Comment by vbezgachev** [comment]
Hi @pharrellyhy 
I have tested batching (sending 8 images for prediction at once instead of one-by-one) over gRPC where the client was responsible for preparing the images; you can find my sample [here](https://github.com/Vetal1977/tf_serving_example/blob/cbdc378aa83625e2dd6edd2d32251ebc4da7ac88/svnh_semi_supervised_client.py#L67). It brought me 2x speedup. I didn't test batching via HTTP and REST but can imagine that it will also improve performance.
